app = "utamikanlist"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  ports = [
    { port = "80", handlers = ["http"] },
    { port = "443", handlers = ["tls", "http"] }
  ]

[[redirects]]
  from = "/list"
  to = "/list.html"
  status = 200
