[build]
  command = "npm install && npm run build"
  publish = "out"

  [[redirects]]
  from = "/list"
  to = "/list.html"
  status = 200

[[headers]]
  for = "/sitemap.xml"  # パス修正（/public/削除）
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
