[functions]
  directory = "netlify/functions"

[build]
  publish = "." # ルートディレクトリに静的ファイルがある場合

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# サイトマップ設定
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=86400, stale-while-revalidate=3600"

# Content Security Policy（CSP）の設定
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.google-analytics.com https://www.googletagmanager.com; img-src 'self' data: https://www.transparenttextures.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;"

# キャッシュ戦略
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000" # 一年単位でキャッシュ

# CORS設定 (APIエンドポイント用)
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# プラグイン設定
[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    exclude = ["/admin/*", "/temp/*"]
    changeFreq = "daily"
    priority = 0.7

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    audits = ["https://utamikan.netlify.app/"] # ここで配列にする
    thresholds = { performance = 90, accessibility = 100, "best-practices" = 90, seo = 90 }
    fail_deploy_on_score_thresholds = true
    
# 開発環境向け追加設定
[dev]
  framework = "static"
  targetPort = 3000 # 適切なポート番号に変更
  autoLaunch = false
