[build]
  functions = "netlify/functions"

  [[redirects]]
  from = "/list"
  to = "/list.html"
  status = 200

# 追加推奨設定（キャッシュ制御例）
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "DENY"
