[build]
  command = "npm run build && cp public/sitemap.xml out/"  # 明示的コピー
  publish = "out"

  [[redirects]]
  from = "/list"
  to = "/list.html"
  status = 200

# netlify.toml
[[headers]]
  for = "/public/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
