[build]
  functions = "netlify/functions"

  [[redirects]]
  from = "/list"
  to = "/list.html"
  status = 200

/robots.txt    /robots.txt   200
/sitemap.xml    /sitemap.xml   200
/*              /index.html    200
