[functions]
  directory = "netlify/functions"

[build]
  publish = "." # ルートディレクトリに静的ファイルがある場合

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# サイトマップ設定
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=86400, stale-while-revalidate=3600"

# セキュリティヘッダー
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# キャッシュ戦略
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=3153600" # 画像ファイルのキャッシュ時間を調整

# CORS設定 (APIエンドポイント用)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# プラグイン設定
[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    exclude = ["/admin/*", "/temp/*"]
    changeFreq = "daily"
    priority = 0.7

[[plugins]]
package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
  audit_url = "https://utamikan.netlify.app/"
  thresholds = { performance = 90, accessibility = 100, "best-practices" = 90, seo = 90 }
  fail_deploy_on_score_thresholds = true


# 開発環境向け追加設定
[dev]
  framework = "static"
  targetPort = 3000 # 適切なポート番号に変更
  autoLaunch = false
