[build]
  functions = "netlify/functions"

  [[redirects]]
  from = "/list"
  to = "/list.html"
  status = 200

# netlify.toml
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"
