[build]
  publish = "." 
  
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"
    Link = "</sitemap.xml>; rel=\"sitemap\""
    
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true  # 必須設定[^1][^3]

[[plugins]]
package = "@netlify/plugin-sitemap"
[plugins.inputs]
buildDir = "public"
changeFreq = "weekly"
priority = 0.5
exclude = ["/secret-page"]
