[build]
  command = "" # または、必要なビルドコマンド
  publish = "." # 公開ディレクトリを明示的に指定（例: public）
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"
    Link = "</sitemap.xml>; rel=\"sitemap\"; type=\"application/xml\""

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://*.googletagmanager.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.google-analytics.com;"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  exclude = ["/admin/*", "/secret/*"]
  changeFreq = "weekly"
  priority = 0.5

[[plugins]]
package = "netlify-plugin-lighthouse"
  [plugins.inputs]
  output_path = "reports/lighthouse.html"  # フォルダ作成必須
  thresholds:  # オプションでスコア基準設定
    performance = 0.9
    accessibility = 0.9
    
[dev]
  framework = "nextjs"
  targetPort = 3000
  autoLaunch = true
  command = "npm run dev"

